---
title: "NTN-F"
output: html_notebook
---

- fazer o apreçamento de NTN-F usando `GetTDData`

```{r}
library(tidyverse)
library(bizdays)
library(GetTDData)
source("Utils/rendafixa-compounding.R")
source("Utils/rendafixa-daycount.R")
source("Utils/rendafixa-spotrate.R")
source("Pricing/fixedrate-bonds.R")

ntnf <- ntnf()
```

```{r}
get_td_files(ntnf)
```

## Selecionando vencimentos

<https://www.tesourodireto.com.br/titulos/precos-e-taxas.htm>

```{r}
maturities <- c("010123", "010125", "010127", "010129", "010131")

df <- read_td_files(ntnf, maturities)
```

```{r}
df %>%
  ggplot(aes(x = ref.date, y = price.bid, group = asset.code, color = asset.code)) +
  geom_line(size = 1)
```

```{r}
df %>%
  ggplot(aes(x = ref.date, y = yield.bid, group = asset.code, color = asset.code)) +
  geom_line(size = 1)
```

## Calculando o preço teórico

$$
VP_t = \sum_{k=1}^{N}\frac{1000\cdot[(1.10)^{0.5}-1]}{(1+y_t)^{t_k}} + \frac{1000}{(1 + y_t)^{t_N}}
$$

```{r}
sel_ntnf <- filter_by_refdates(ntnf, df, Sys.Date() %>% following("Brazil/ANBIMA"))
```


```{r}
sel_ntnf <- price_from_rate(ntnf, sel_ntnf)
```



